name: Publish langfuse to Artifact Hub
run-name: Publish langfuse to Artifact Hub
on: workflow_dispatch
env:
  LANGFUSE_VERSION: "1.1.0"
jobs:
  langfuse:
    name: Publish langfuse to Artifact Hub
    runs-on: ubuntu-latest
    steps:
      - name: Download Langfuse tar file
        run: |
          curl -L -o langfuse-${{ env.LANGFUSE_VERSION }}.tgz https://github.com/langfuse/langfuse-k8s/releases/download/langfuse-${{ env.LANGFUSE_VERSION }}/langfuse-${{ env.LANGFUSE_VERSION }}.tgz
      - name: Extract tar file
        run: |
          tar -xzf langfuse-${{ env.LANGFUSE_VERSION }}.tgz
          cd langfuse-${{ env.LANGFUSE_VERSION }}
      - name: Copy langfuse directory into current directory
        run: |
          cp -r langfuse-${{ env.LANGFUSE_VERSION }}/* .
      - name: Delete langfuse directory
        run: |
          rm -rf langfuse-${{ env.LANGFUSE_VERSION }}
      - name: Show contents of current directory
        run: |
          ls -la
      - name: Show contents of langfuse directory
        run: |
          ls -la langfuse
