name: Publish langfuse to Artifact Hub
run-name: Publish langfuse to Artifact Hub
on: workflow_dispatch
env:
  LANGFUSE_VERSION: "1.1.0"
permissions:
  contents: write
jobs:
  langfuse:
    name: Publish langfuse to Artifact Hub
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Check if langfuse tgz already exists
        id: check_file
        run: |
          if [ -f "langfuse-${{ env.LANGFUSE_VERSION }}.tgz" ]; then
            echo "Langfuse package already exists. Stopping workflow."
            exit 1
          fi

      - name: Download Langfuse tar file
        run: |
          curl -L -o langfuse-${{ env.LANGFUSE_VERSION }}.tgz https://github.com/langfuse/langfuse-k8s/releases/download/langfuse-${{ env.LANGFUSE_VERSION }}/langfuse-${{ env.LANGFUSE_VERSION }}.tgz

      - name: Extract tar file and check structure
        run: |
          tar -xzf langfuse-${{ env.LANGFUSE_VERSION }}.tgz
          ls -la

      - name: Show final directory structure
        run: |
            ls -la ./langfuse
      
      - name: Delete tgz file
        run: |
          rm langfuse-${{ env.LANGFUSE_VERSION }}.tgz

      - name: Package the chart
        working-directory: ./langfuse
        run: |
          helm package . -d ../
      
      - name: Remove langfuse directory
        run: |
          rm -rf langfuse
      
      - name: Show final directory structure
        run: |
            ls -la
      
      - name: Create index file
        run: |
          helm repo index --url https://github.com/skyu-io/langfuse-helm-chart/ .
      
      - name: Push the changes to github
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add . 
          git commit -m "Added langfuse-${{ env.LANGFUSE_VERSION }}.tgz"
          git push